const users = require('./users/users.service.js');
const soal = require('./soal/soal.service.js');
const kelas = require('./kelas/kelas.service.js');
const siswa = require('./siswa/siswa.service.js');
const pelajaran = require('./pelajaran/pelajaran.service.js');
const guru = require('./guru/guru.service.js');
const upload = require('./upload/upload.service.js');
const exportUsers = require('./export/users/users.service.js');
const admin = require('./admin/admin.service.js');
const excelSoal = require('./excel-soal/excel-soal.service.js');
const dashboard = require('./dashboard/dashboard.service.js');
const messages = require('./messages/messages.service.js');
const authManagement = require('./auth-management/auth-management.service.js');
const email = require('./email/email.service.js');
const complaints = require('./complaints/complaints.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(soal);
  app.configure(kelas);
  app.configure(siswa);
  app.configure(pelajaran);
  app.configure(guru);
  app.configure(upload);
  app.configure(exportUsers);
  app.configure(admin);
  app.configure(excelSoal);
  app.configure(dashboard);
  app.configure(messages);
  app.configure(authManagement);
  app.configure(email);
  app.configure(complaints);
};
